In [7]:
#Exercise 1
import numpy as np

array_a = np.arange(1,10)
print(array_a)

[1 2 3 4 5 6 7 8 9]


In [8]:
#Exercise 2
import numpy as np

unstructured_list = [3.14, 2.17, 0, 1, 2]
array_int = np.array(unstructured_list, dtype=int)
print(array_int)

[3 2 0 1 2]


In [9]:
#Exercise 3
import numpy as np

array_3x3 = np.arange(1,10).reshape(3,3)
print(array_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#Exercise 4
import numpy as np

array_2d = np.random.rand(4,5)
print(array_2d)

[[0.75202426 0.69896068 0.63319108 0.01483724 0.33217097]
 [0.0543165  0.2058093  0.38309829 0.96687734 0.2870298 ]
 [0.75438749 0.51774646 0.40531243 0.57943246 0.18068317]
 [0.55285994 0.47956593 0.27536256 0.59676482 0.8183856 ]]


In [14]:
#Exercise 5
import numpy as np

print(array_2d[2,:])

[0.75438749 0.51774646 0.40531243 0.57943246 0.18068317]


In [15]:
#Exercise 6

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]

print(reversed_arr)

[5 4 3 2 1]


In [16]:
#Exercise 7

import numpy as np

matrix = np.arange(1,17)

reshaped_arr = matrix.reshape(4,4)

print(reshaped_arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [19]:
#Exercise 8

import numpy as np

sum_matrix = np.sum(matrix)
avg_matrix = np.mean(matrix)

print('Sum:', sum_matrix, 'Average:', avg_matrix)

Sum: 136 Average: 8.5


In [20]:
#Exercise 9

import numpy as np

arr_20 = np.arange(1,21)
reshape_arr_20 = np.reshape(arr_20, (4,5))

print(reshape_arr_20)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
#Exercise 10

import numpy as np

arr = np.arange(1, 10)
odd_numbers = arr[arr % 2 == 1]

print(odd_numbers)

[1 3 5 7 9]
